// ============================================================
// PF Claim Decoder — Synthetic Demo Scenarios
// ============================================================
// All data is SYNTHETIC. All names are fictional.
// Reference numbers use DEMO-CLM-2026-XXX format.
// ============================================================

import { DemoScenario } from './types';

export const DEMO_SCENARIOS: DemoScenario[] = [
  {
    id: 'demo-1',
    label: 'Aadhaar Name Mismatch',
    labelHi: 'आधार नाम विसंगति',
    claimantName: 'Aarav Mehta',
    claimReference: 'DEMO-CLM-2026-001',
    claimType: 'pf_withdrawal',
    remark: 'Claim returned due to mismatch in name with Aadhaar-linked records.',
    remarkHi: 'आधार-लिंक्ड रिकॉर्ड में नाम में विसंगति के कारण दावा लौटाया गया।',
    submissionDate: '2026-07-15',
    employerState: 'approved',
    kycState: 'partial',
    sector: 'Manufacturing',
    expectedCategoryId: 'aadhaar_mismatch',
  },
  {
    id: 'demo-2',
    label: 'Employer Approval Pending',
    labelHi: 'नियोक्ता स्वीकृति लंबित',
    claimantName: 'Priya Sharma',
    claimReference: 'DEMO-CLM-2026-002',
    claimType: 'pf_withdrawal',
    remark: 'Claim pending for employer approval.',
    remarkHi: 'दावा नियोक्ता स्वीकृति के लिए लंबित।',
    submissionDate: '2026-07-20',
    employerState: 'pending',
    kycState: 'complete',
    sector: 'IT Services',
    expectedCategoryId: 'employer_non_approval',
  },
  {
    id: 'demo-3',
    label: 'Generic Verification Pending',
    labelHi: 'सामान्य सत्यापन लंबित',
    claimantName: 'Rohan Gupta',
    claimReference: 'DEMO-CLM-2026-003',
    claimType: 'pf_withdrawal',
    remark: 'Verification pending.',
    remarkHi: 'सत्यापन लंबित।',
    submissionDate: '2026-06-10',
    employerState: 'unknown',
    kycState: 'unknown',
    sector: 'Retail',
    expectedCategoryId: 'verification_pending',
  },
  {
    id: 'demo-4',
    label: 'Past 20-Day Timeline — No Response',
    labelHi: '20-दिन की समयसीमा पार — कोई जवाब नहीं',
    claimantName: 'Kavita Patel',
    claimReference: 'DEMO-CLM-2026-004',
    claimType: 'pension',
    remark: 'No meaningful response after the stated service timeline.',
    remarkHi: 'निर्धारित सेवा समयसीमा के बाद कोई सार्थक प्रतिक्रिया नहीं।',
    submissionDate: '2026-06-01',
    employerState: 'approved',
    kycState: 'complete',
    sector: 'Education',
    expectedCategoryId: 'past_20_day_no_response',
    syntheticAgeDays: 31,
  },
  {
    id: 'demo-5',
    label: 'Duplicate Claim Flagged',
    labelHi: 'डुप्लिकेट दावा चिह्नित',
    claimantName: 'Vikram Singh',
    claimReference: 'DEMO-CLM-2026-005',
    claimType: 'pf_transfer',
    remark: 'Duplicate claim already exists for this member.',
    remarkHi: 'इस सदस्य के लिए डुप्लिकेट दावा पहले से मौजूद है।',
    submissionDate: '2026-07-25',
    employerState: 'approved',
    kycState: 'complete',
    sector: 'Construction',
    expectedCategoryId: 'duplicate_claim_flagged',
  },
  {
    id: 'demo-6',
    label: 'KYC Incomplete',
    labelHi: 'KYC अधूरा',
    claimantName: 'Sneha Reddy',
    claimReference: 'DEMO-CLM-2026-006',
    claimType: 'pf_advance',
    remark: 'Claim cannot be processed as KYC verification is pending.',
    remarkHi: 'KYC सत्यापन लंबित होने के कारण दावा संसाधित नहीं किया जा सकता।',
    submissionDate: '2026-08-01',
    employerState: 'approved',
    kycState: 'partial',
    sector: 'Healthcare',
    expectedCategoryId: 'kyc_incomplete',
  },
  {
    id: 'demo-7',
    label: 'Missing Exit Date',
    labelHi: 'निकास तिथि गायब',
    claimantName: 'Arjun Nair',
    claimReference: 'DEMO-CLM-2026-007',
    claimType: 'pf_withdrawal',
    remark: 'Exit date not updated by employer. Claim cannot proceed.',
    remarkHi: 'नियोक्ता द्वारा निकास तिथि अपडेट नहीं की गई। दावा आगे नहीं बढ़ सकता।',
    submissionDate: '2026-07-10',
    employerState: 'pending',
    kycState: 'complete',
    sector: 'Textiles',
    expectedCategoryId: 'missing_exit_date',
  },
];
